### ISSUE TITLE
Version up Node

### ISSUE THREAD

**Issue by kaito0228** [Code-Hex/gqldoc-actions#1]
Hi, Always handy!
Thank you!
I am getting a warning that the Node is out of date, can you please address this?

<img width="1355" alt="image" src="https://user-images.githubusercontent.com/39002408/203200446-aab2c061-e4b7-47a7-831e-5dcf409b6b00.png">

**Comment by Code-Hex** [comment]
@kaito0228 I just published this fix as the latest

**Comment by kaito0228** [comment]
Thank you for quick response!
